apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: prod-dmarc-exporter

commonLabels:
  app: prod-dmarc-exporter

images:
  - name: dmarc-exporter
    newName: repo.campos.rj.gov.br/dmarc-exporter
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/suspend
        value: false
    target:
      kind: CronJob
      name: dmarc-exporter-cronjob
