apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml
- dmarc-exporter-sealedsecret.yaml
# - deployment.yaml

namespace: staging-dmarc-exporter

commonLabels:
  app: prod-dmarc-exporter

images:
- name: dmarc-exporter
  newName: igormagrodmarc/dmarc-exporter
  newTag: stg-edc3e248

patches:
- patch: |-
    - op: replace
      path: /spec/suspend
      value: false
  target:
    kind: CronJob
    name: dmarc-exporter-cronjob
